export const BASE_URL = 'http://localhost:8080';

export const Urls = {
  LOGIN: '/auth',
  REGISTRATION: '/registration',
  CLIENTS: '/clients',
  CLIENT_IMPORT: '/clients/upload-excel',
  ONLINE_BUYS: '/online/buys',
  ONLINE_BUYS_DETAILS: '/online/buys/details',
  OFFLINE_BUYS: '/offline/points/buys',
  OFFLINE_BUYS_IMPORT: '/offline/points/buys/upload-excel',
  OFFLINE_BUYS_DETAILS: '/offline/points/buys/details',
  OFFLINE_POINTS_PRODUCTS: '/offline/points/products',
  POINTS: '/points',
  OFFLINE_POINTS: '/points/offline',
  CATEGORIES: '/categories',
  PRODUCTS: '/products',
  PROFILES: '/profiles',
  REGIONS: '/regions',
  REPORT: '/report',

  ANALYTICS_ONLINE_ABC: '/analytics/online/abc',
  ANALYTICS_ONLINE_XYZ: '/analytics/online/xyz',
  ANALYTICS_ONLINE_GENERAL: '/analytics/online/general',
  ANALYTICS_ONLINE_GROWTH: '/analytics/online/growth',
  ANALYTICS_ONLINE_PROFITABILITY: '/analytics/online/profitability',
  ANALYTICS_ONLINE_BY_CATEGORY: '/analytics/online/category',
  ANALYTICS_ONLINE_REGIONS: '/analytics/online/region',
  ANALYTICS_ONLINE_CUSTOMERS: '/analytics/online/customers',

  ANALYTICS_OFFLINE_ABC: '/analytics/offline/abc',
  ANALYTICS_OFFLINE_XYZ: '/analytics/offline/xyz',
  ANALYTICS_OFFLINE_GENERAL: '/analytics/offline/general',
  ANALYTICS_OFFLINE_GROWTH: '/analytics/offline/growth',
  ANALYTICS_OFFLINE_PROFITABILITY: '/analytics/offline/profitability',
  ANALYTICS_OFFLINE_BY_CATEGORY: '/analytics/offline/category',
  ANALYTICS_OFFLINE_REGIONS: '/analytics/offline/region',
  ANALYTICS_OFFLINE_ASSORTMENT: '/analytics/offline/assortment',

  ANALYTICS_TOTAL_ABC: '/analytics/total/abc',
  ANALYTICS_TOTAL_XYZ: '/analytics/total/xyz',
  ANALYTICS_TOTAL_GENERAL: '/analytics/total/general',
  ANALYTICS_TOTAL_GROWTH: '/analytics/total/growth',
  ANALYTICS_TOTAL_PROFITABILITY: '/analytics/total/profitability',
  ANALYTICS_TOTAL_BY_CATEGORY: '/analytics/total/category',
  ANALYTICS_TOTAL_REGIONS: '/analytics/total/region',
}